version: '3'
services:
        pgdb:
                image: postgres:latest
                restart: always
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_DB: hyfy
                ports:
                        - "5432:5432"
        redis:
                image: redis:latest
        api:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./server
                volumes:
                        - /app/node_modules
                        - ./server:/usr/app
                environment:
                        - POSTGRES_DBNAME=hyfy
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_HOST=pgdb
                        - POSTGRES_PORT=5432
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                ports:
                        - "3000:3000"     
                  
        # client:
        #         build:
        #                 dockerfile: Dockerfile.dev
        #                 context: ./client
        #         volumes:
        #                 - /app/node_modules
        #                 - ./client:/app
        # # worker:
        #         build:
        #                 dockerfile: Dockerfile.dev
        #                 context: ./worker
        #         volumes:
        #                 - /app/node_modules
        #                 - ./worker:/app
        
        # nginx:
        #         restart: always
        #         build:
        #                 dockerfile: Dockerfile.dev
        #                 context: ./nginx
        #         ports:
        #                 - "3000:80"